http:
  port: ${PORT:-3000}
admin:
  port: 9876
  host: localhost
apiEndpoints:
  products:
    host: "*"
    paths: ["/products", "/products/*", "/uploadImage"]
  authentication:
    host: "*"
    paths: ["/auth/*"]
  customers:
    host: "*"
    paths: ["/customers", "/customers/*"]
  toasters:
    host: "*"
    paths: ["/toasters", "/toasters/*"]
  deliveries:
    host: "*"
    paths: ["/deliveries"]
  billing-profile:
    host: "*"
    paths: ["/billing-profile"]
  history:
    host: "*"
    paths: ["/history"]
  payment:
    host: "*"
    paths: ["/payment"]
  subscription:
    host: "*"
    paths: ["/subscription"]
  stripewebhook:
    host: "*"
    paths: ["/stripewebhook"]
serviceEndpoints:
  productsService:
    url: ${PRODUCTS_URL}
  usersService:
    url: ${USERS_URL}
  deliveriesService:
    url: ${DELIVERIES_URL}
  salesService:
    url: ${SALES_URL}
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  productsPipeline:
    apiEndpoints:
      - products
    policies:
      # Uncomment `key-auth:` when instructed to in the Getting Started guide.
      # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: productsService
              changeOrigin: true
  usersPipeline:
    apiEndpoints:
      - authentication
      - customers
      - toasters
    policies:
      # Uncomment `key-auth:` when instructed to in the Getting Started guide.
      # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: usersService
              changeOrigin: true
  deliveriesPipeline:
    apiEndpoints:
      - deliveries
    policies:
      # Uncomment `key-auth:` when instructed to in the Getting Started guide.
      # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: deliveriesService
              changeOrigin: true
  salesPipeline:
    apiEndpoints:
      - billing-profile
      - history
      - payment
      - subscription
      - stripewebhook
    policies:
      # Uncomment `key-auth:` when instructed to in the Getting Started guide.
      # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: salesService
              changeOrigin: true
