http:
  port: ${PORT:-3000}
admin:
  port: 9876
  host: ${HOST:-localhost}
apiEndpoints:
  products:
    host: ${HOST:-localhost}
    paths: ["/products", "/products/*"]
  authentication:
    host: ${HOST:-localhost}
    paths: ["/auth/*"]
  customers:
    host: ${HOST:-localhost}
    paths: ["/customers", "/customers/*"]
  toasters:
    host: ${HOST:-localhost}
    paths: ["/toasters", "/toasters/*"]
  deliveries:
    host: ${HOST:-localhost}
    paths: ["/deliveries"]
  returns:
    host: ${HOST:-localhost}
    paths: ["/returns"]
  billing-profile:
    host: ${HOST:-localhost}
    paths: ["/billing-profile"]
  history:
    host: ${HOST:-localhost}
    paths: ["/history"]
  payment:
    host: ${HOST:-localhost}
    paths: ["/payment"]
  return:
    host: ${HOST:-localhost}
    paths: ["/return"]
  subscription:
    host: ${HOST:-localhost}
    paths: ["/subscription"]
serviceEndpoints:
  productsService:
    url: "https://coffaine-products.herokuapp.com/api/v1"
  usersService:
    url: "https://coffaine-users.herokuapp.com/api/v1"
  deliveriesService:
    url: "https://coffaine-deliveries.herokuapp.com/api/v1"
  salesService:
    url: "https://coffaine-sales.herokuapp.com/api/v1"
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  productsPipeline:
    apiEndpoints:
      - products
    policies:
      # Uncomment `key-auth:` when instructed to in the Getting Started guide.
      # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: productsService
              changeOrigin: true
  usersPipeline:
    apiEndpoints:
      - authentication
      - customers
      - toasters
    policies:
      # Uncomment `key-auth:` when instructed to in the Getting Started guide.
      # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: usersService
              changeOrigin: true
  deliveriesPipeline:
    apiEndpoints:
      - deliveries
      - returns
    policies:
      # Uncomment `key-auth:` when instructed to in the Getting Started guide.
      # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: deliveriesService
              changeOrigin: true
  salesPipeline:
    apiEndpoints:
      - billing-profile
      - history
      - payment
      - return
      - subscription
    policies:
      # Uncomment `key-auth:` when instructed to in the Getting Started guide.
      # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: salesService
              changeOrigin: true
